name: TaskList Refactoring for Java

on:
  push:
    branches:
      - main
    paths:
      - 'java/**'
      - '.github/workflows/java.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'java/**'
      - '.github/workflows/java.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout/@v4

      - name: Set up JDK 23
        uses: actions/setup-java/@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Build
        run: |
          cd java
          mvn -B package
    
